// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import CustomTabsController from "./custom_tabs_controller"
import SearchFormController from "./search_form_controller"
import ScrollController from "./scroll_controller"
import OrderItemQuantityController from "./order_item_quantity_controller"
import PaginationController from "./pagination_controller"
import { Alert, Dropdown } from "tailwindcss-stimulus-components"

application.register("hello", HelloController)
application.register("alert", Alert)
application.register("tabs", CustomTabsController)
application.register('dropdown', Dropdown);
application.register("search-form", SearchFormController)
application.register("scroll", ScrollController)
application.register("order-item-quantity", OrderItemQuantityController)
application.register("pagination", PaginationController)
