// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import { Alert, Tabs, Dropdown } from "tailwindcss-stimulus-components"

application.register("hello", HelloController)
application.register("alert", Alert)
application.register("tabs", Tabs)
application.register('dropdown', Dropdown);
